### ISSUE TITLE
Beta 7.5: Editing Sum formula box requires more than one mouse click to activate

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#382] opened 2019-05-03 14:57 UTC
See title, happens when editing a formula. The cursor is blinking, but no keyboard entry is accepted.

**Comment by Yuri05** [comment] 2019-05-03 15:10
happens to me as well...

**Comment by msevestre** [comment] 2019-05-03 15:40
I can't reproduce. Does it happen all the time ? Are you on your computer or using a remote desktop session?

**Comment by Yuri05** [comment] 2019-05-03 15:41
local computer, not always reproducible as well...

**Comment by msevestre** [comment] 2019-06-08 08:29
closing. Please reopen if there is a way to reproduce

**Closed by msevestre** 2019-06-08 08:29 UTC
Labels: unable to reproduce
