### ISSUE TITLE
"Expected number of solver warning does not match"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#506] opened 2020-08-25 14:04 UTC
What exactly does it mean? Getting this since V9 now and then.

**Comment by msevestre** [comment] 2020-08-25 14:46
You are going to have to explain what you mean here.

**Comment by PavelBal** [comment] 2020-08-26 10:42
Sometimes simulations fail (or PI runs fail) with the above mentioned message.

**Comment by PavelBal** [comment] 2020-11-03 15:10
@msevestre Do you still require more feedback? What kind of feedback?

**Comment by msevestre** [comment] 2020-11-03 16:12
Yes. In order to solve an issue, we need to reproduce. IF we can't reproduce, we can't solve :)

**Comment by PavelBal** [comment] 2020-11-09 11:58
Example simulation provided.

**Comment by Yuri05** [comment] 2021-08-23 09:02
fixed in V10

**Closed by Yuri05** 2021-08-23 09:02 UTC
Labels: feedback required
