### ISSUE TITLE
Comparison of MSV BBs - list "Molecule name" and "Path" separately

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#835] opened 2022-12-13 16:16 UTC
Comparison of MSV BBs lists the entries as "Path" and "Molecule" combined in the column "Object"

![image](https://user-images.githubusercontent.com/25903040/207385971-f177bbdb-7488-46b1-a63c-ca1fe0234956.png)

Having separate columns for "Path" and "Molecule" would allow to filter for molecule or a container of interest.

**Comment by rwmcintosh** [comment] 2023-01-17 13:41
@PavelBal 

You can create some sophisticated filters using the grid control.

Right click on the 'Object' caption

![image](https://user-images.githubusercontent.com/261477/212913314-25bff8cd-d1b5-4d6d-bd13-3ec8ce3f148e.png)

Show the filter editor and then you can create filters for strings and you can combine them with logical operations

![image](https://user-images.githubusercontent.com/261477/212913771-dc9553f2-4640-4e20-8762-2bc7f256f7e4.png)

This doesn't allow sorting, but if the goal is to isolate the view to the named molecule than this might do the trick

**Comment by msevestre** [comment] 2023-01-20 16:47
Path structure (I think)

Simulation. Not required

Then assuming a standard path with at least 2 entries

Last: NamePathElement
First: TopContainerPathElement

IF you have more entries
* For Molecule and Expression
  => One before last is MoleculePathElement
* For other, 
 => One before last is BottomCompartmentPathElement

Then you take whatever is left and put in into ContainerPathElement (and in BottomCompartmentPathElement if you had a molecule)
IF more than one entries, concatenate using the separator used in the PathElementMapper


so Organism|Liver|PeriportalIntracellular|Drug|Concentration

Name: Concentration
Molecule:Drug
Top: Organism
BottomContainer: Intracellular
Container: Liver-Periportal

**Comment by rwmcintosh** [comment] 2023-01-24 16:04
I think in the case of MSV and Expression the 'Name' is the 'MoleculeName', so all the indexes still line up, but we can have this additional property 'MoleculeName' which is a duplicate of 'Name'

![image](https://user-images.githubusercontent.com/261477/214344619-69ead300-8f7d-4a75-b963-90dccab8396d.png)

**Comment by rwmcintosh** [comment] 2023-01-25 13:12
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1876](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1876) via [**Zenhub**](https://www.zenhub.com/)

**Closed by rwmcintosh** 2023-01-25 13:12 UTC
