### ISSUE TITLE
Display issue in MSV and PSV

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/MoBi#409] opened 2019-07-22 09:30 UTC
In OSP v8.0 build 21 the display of the PSV is faulty: 

![Untitled](https://user-images.githubusercontent.com/26541603/61621802-e5e94f80-ac73-11e9-8489-f9e4b89863ac.jpg)

the same is true for the Molecule Start Values:
![Untitled](https://user-images.githubusercontent.com/26541603/61697240-2231b400-ad37-11e9-9a81-c87ff626dc2d.jpg)

**Comment by msevestre** [comment] 2019-07-23 15:29
![image](https://user-images.githubusercontent.com/1041237/61725073-1ba63b00-ad3d-11e9-9e0d-c58cd8b6aa79.png)

Do you have some special font scaling or sthg?

**Comment by AndreDlm** [comment] 2019-07-23 16:39
Not that I am aware of. I did neither change any settings when upgrading from v7 to 8.

**Comment by Yuri05** [comment] 2019-07-23 21:08
Cannot reproduce...

**Comment by msevestre** [comment] 2019-07-23 21:11
What theme are you using?

**Comment by AndreDlm** [comment] 2019-07-24 06:53
The default theme

**Comment by Yuri05** [comment] 2019-07-24 07:32
@AndreDlm 
Can you remove `C:\Users\<USER_ID>\AppData\Roaming\Open Systems Pharmacology\MoBi\8.0\Settings.xml` and restart MoBi?

**Comment by AndreDlm** [comment] 2019-07-24 08:15
Done, but it didn't resolve the issue

**Comment by AndreDlm** [comment] 2019-07-24 11:26
Ok, when I change the text size on my screen to any non-default value (100% and 150%), everything is correctly displayed. However, when using the default option (125%), the display is messed

**Comment by Yuri05** [comment] 2019-07-24 12:27
>Ok, when I change the text size on my screen to any non-default value (100% and 150%), everything is correctly displayed. However, when using the default option (125%), the display is messed

@msevestre Greetings from `SetDPIAware`? Should we allow `SetDPIAware `at least as _command-line option_ for PK-Sim and MoBi?

**Comment by msevestre** [comment] 2019-07-24 12:51
This was never on in MoBi. Only in PKSim. I think we need to revisit some of our controls to work properly.

**Comment by Yuri05** [comment] 2019-07-24 13:11
>This was never on in MoBi. Only in PKSim. I think we need to revisit some of our controls to work properly.

If we will not find a way, it would be at least a workaround. Currently e.g. at 150% font size PK-Sim and MoBi look like 💩

**Comment by Yuri05** [comment] 2022-11-08 13:02
should be fixed in the meanwhile. closing

**Closed by Yuri05** 2022-11-08 13:02 UTC
