### ISSUE TITLE
Exception when removing a molecule from the Reactions-Diagram

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#130] opened 2017-07-03 13:37 UTC
1) Open attached project
2) Open the reactions-BB
3) Try to remove the unconnected (to the right) molecule "a".
Application:
MoBi 7.1.0 - Build 66

No component for supporting the service MoBi.Core.Services.IDiagramUpdater was found

Stack trace:
```
at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at MoBi.Core.Domain.Model.MoBiContext.Resolve[T]()
   at MoBi.Core.Services.RemoveMoleculeFromReactionBuildingBlockCommand.ExecuteWith(IMoBiContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.RemoveMoleculeNode(MoleculeNode moleculeNode)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.removeItem(GoObject itemToDelete)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at MoBi.UI.Presenters.ReactionDiagramPresenter.RemoveSelection(IReadOnlyList`1 objectsToBeRemoved)
   at MoBi.UI.Views.ReactionDiagram.ReactionDiagramView.OnSelectionDeleting(CancelEventArgs e)
   at MoBi.UI.Views.BaseDiagram.MoBiBaseDiagramView.<>c__DisplayClass5_1.<InitializeResources>b__3()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

[Diagram_MOlecules_Bug.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1119678/Diagram_MOlecules_Bug.zip)

**Comment by msevestre** [comment] 2017-07-03 14:56
This is a duplicate of 
https://github.com/Open-Systems-Pharmacology/MoBi/issues/110

**Closed** 2017-07-03 14:57 UTC
