### ISSUE TITLE
Event Assignment - allow entering changed path

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#164] opened 2017-08-07 09:40 UTC
For some unknown reason, one cannot manually enter the path to the object to be changed. Instead, the user has to navigate through the parameters tree.

Entering the path manually would save much time.
![eventpath](https://user-images.githubusercontent.com/25903040/29021271-3ba282bc-7b65-11e7-94a1-39b3e350ec33.JPG)

**Comment by UlrichSi** [comment] 2019-06-04 11:00
I would like to support this request. 
1. The tree is severely restricting the options for the changed entity.
2. The changed entity path is only represented as absolute path, whereas PK-Sim-imported paths generally show relative paths.

**Comment by msevestre** [comment] 2021-03-10 18:05
duplicates #485

**Comment by msevestre** [comment] 2021-03-15 18:42
@PavelBal This is much harder here as you also need a dimension to create the formula etc...

So not having an entity is an issue at the moment

**Comment by PavelBal** [comment] 2021-03-15 19:24
Aaaah it's because it is a formula that must be of a certain dimension... This is very unfortunate. Can a manual dimension selection be added?

**Comment by msevestre** [comment] 2021-03-15 19:31
yes for sure. But this is quite some work to make it right

**Comment by msevestre** [comment] 2021-03-15 19:32
so not for this version unfortunately

**Comment by Yuri05** [comment] 2021-09-02 15:49
duplicate of https://github.com/Open-Systems-Pharmacology/MoBi/issues/485

**Comment by PavelBal** [comment] 2021-09-03 08:44
These are two different fields, and this one is still not editable: 
![image](https://user-images.githubusercontent.com/25903040/131977379-fe00b312-4fed-4208-acd0-447ab3097821.png)

**Comment by PavelBal** [comment] 2021-09-03 08:44
@Yuri05 @msevestre

**Closed** 2024-05-02 10:09 UTC
Labels: type: task
