### ISSUE TITLE
11.1 Observed data Tab not refreshed after adding observed data to chart

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#799] opened 2022-11-15 19:16 UTC
Directly after adding to the chart:
![grafik](https://user-images.githubusercontent.com/25061876/202005988-bbc4827d-16ee-4002-845a-307968f780b6.png) ![grafik](https://user-images.githubusercontent.com/25061876/202006055-52421007-eea5-407f-b205-5c836104ac55.png)

After closing and reopen simulation: 
![grafik](https://user-images.githubusercontent.com/25061876/202006208-d1ca7db2-4b88-42d4-ac13-e808133f0275.png)

**Comment by rwmcintosh** [comment] 2022-11-16 19:15
@Yuri05 if you have this exact project then I'd like to try with it. For my test project the output mapping is getting added when I drop observed data on the chart.

It could be because we've added a few events over the past day or so to handle refreshing, but I'd like to see if there's something else.

**Comment by Yuri05** [comment] 2022-11-16 19:46
Here is the MoBi project: [P3.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/10025132/P3.zip)
Try to add any of observed data sets to the simulation

Originally created in PK-Sim and sent to MoBi. Here you could remove obs data and add it again - it gets automatically mapped.
[Alfentanil_11.1_Tests_K2011.pksim5.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/10025175/Alfentanil_11.1_Tests_K2011.pksim5.zip)

**Comment by Yuri05** [comment] 2022-11-16 20:45
Todays results look definitely better :)

**Comment by rwmcintosh** [comment] 2022-11-17 12:22
ok, let's close this one. It's been fixed along the way.

**Comment by Yuri05** [comment] 2022-11-30 13:36
MoBi 11.1.90: the issue is again here

**Comment by PavelBal** [comment] 2022-12-05 21:23
Cannot reproduce. Latest MoBi nightly (11.1.93), downloaded P4 from here https://github.com/Open-Systems-Pharmacology/MoBi/issues/800

Open simulation, dradndropp all obs data to the "Results"-tab, switch to "Observed data" - all is mapped there.

**Comment by Yuri05** [comment] 2022-12-06 09:13
Reproducible on my computer with 11.1.93 and P4. Showed it yesterday to @rwmcintosh

**Comment by msevestre** [comment] 2022-12-06 13:35
This is working for me
![image](https://user-images.githubusercontent.com/1041237/205926506-23afe8f8-89b6-494c-b0aa-e2c4c1850655.png)

**Comment by rwmcintosh** [comment] 2022-12-06 14:07
I suggest that Juri and I sit together and run this through the debugger on his PC so we can understand what's going on. I have emailed him to suggest a time.

**Closed** 2022-12-08 16:11 UTC
Labels: subsystem: UI, type: bug
