### ISSUE TITLE
Results Chart: Full contect menu is missing.

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#66] opened 2017-04-12 12:44 UTC
When right-clicking into the chart, its context menu currently has only "copy as image". Resetting the zoom factor is missing, as is "Export to Excel" and "Export to PDF".

**Comment by msevestre** [comment] 2017-04-12 12:53
This is a duplicate of Open-Systems-Pharmacology/PK-Sim#97

**Comment by UlrichSi** [comment] 2017-04-12 12:55
I changed the title. The PK-Sim issue does not mention the other items.

**Comment by rwmcintosh** [comment] 2017-04-12 13:01
Duplicate, but OSPSuite.Core was not updated in MoBi yet.

**Comment by msevestre** [comment] 2017-04-12 13:07
yes that's why I did not close it yet. I will have to update core in MoBi when I do the fix for SX.dll anyways

**Comment by UlrichSi** [comment] 2017-04-12 14:10
Ok, I'll better wait til things are updated here. - The "Time Profile" plots obtainable after "Parameter Identification" also look strange, if solid lines are chosen. It looks like they are faintly dotted instead of solid, or sometimes missing at all.

**Comment by msevestre** [comment] 2017-04-12 14:22
This is something different here (and probably not new). Can you please
create another entry for that?

**Comment by msevestre** [comment] 2017-04-12 18:07
This is now fixed

**Closed by msevestre** 2017-04-12 18:07 UTC
