### ISSUE TITLE
Export of an organ to PKML - combine "Save to pkml" and "Save to pkml with individual"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1238] opened 2023-12-13 12:26 UTC
I think we should have only one menu entry "Save to pkml", and in the next step the user decides whether to export with individual or not.

**Comment by rwmcintosh** [comment] 2024-01-18 11:59
@PavelBal This is a duplicate of #1145 ?

**Comment by rwmcintosh** [comment] 2024-01-18 12:01
At least, since we already implemented the Individuals. It's probably more accurate to close #1145 and leave this one open since we are starting with already working container and individual export.

**Comment by PavelBal** [comment] 2024-01-18 12:36
> This is a duplicate of https://github.com/Open-Systems-Pharmacology/MoBi/issues/1145 ?

Almost, #1145 now combines a set of issues, I think.. This issue here does not mention expression profiles.

**Comment by rwmcintosh** [comment] 2024-01-18 13:04
Yes, but the only portion remaining from that original set of issues is this one. I can probably close one or the other.

**Comment by rwmcintosh** [comment] 2024-04-18 17:50
This has been done already.

**Closed by rwmcintosh** 2024-04-18 17:50 UTC
