### ISSUE TITLE
Clarify that PV's are always committed to the last building block in the configuration

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/MoBi#1716] opened 2024-12-17 10:20 UTC
At the simulation "Human_IV" (attached project), 
[adminParam.zip](https://github.com/user-attachments/files/18163810/adminParam.zip)

I changed a parameter related to the administration in the module " AdminEvents_IV_humanTwoCompartments”. After committing to the building block, a new PV is added to the unrelated module “General_Parameters_Molecules_Observers”. I would expect a new PV in the module “AdminEvents_IV_humanTwoCompartments” and I’m pretty sure it worked as expected few builds before (done now with build 396).

**Comment by Christoph27** [comment] 2024-12-17 10:38
I was trying to find the build for which it worked, but was not able find it. Thus, I think that there has nothing changed from one build to another, but that there might be a different problem: I renamed the module (and maybe some other elements within the module). Could it be that the correct module is not found any more due to the re-naming?

**Comment by rwmcintosh** [comment] 2024-12-17 11:57
The commit happened this way by design. The issue is that we have combined a bunch of modules into a simulation and we cannot trace each simulation parameter back to it's source building block for certain. So we always add the PV to the last building block in the configuration.

![image](https://github.com/user-attachments/assets/29feb878-e67a-47b4-a576-295c7ebb1fce)

Could it be that previously when you committed the simulation changes the apparently correct module was the last one in the configuration.

At minimum, we can explain this in the commit message.

**Comment by Christoph27** [comment] 2024-12-17 14:00
Yes, coincidently until now the “correct” module to which I wanted to commit parameters was always the last one in the configuration list. Thus, I thought MoBi would know to which module a parameter belongs still at the simulation. Good to know now that it is different ....  Maybe it then rather a feature whish for the future: being able to select the module to which the PV building block is going to be added …

**Comment by rwmcintosh** [comment] 2024-12-17 14:18
We have this one as TODO https://github.com/Open-Systems-Pharmacology/MoBi/issues/1614

I'm going to keep this one, but rename it slightly to indicate that the confirmation dialog should not only show where the PV are added, but at least a little bit of the why.

**Comment by rwmcintosh** [comment] 2024-12-17 14:19
We just have to add something like
"Parameter Values are always added in the last module of the simulation configuration"

**Closed** 2024-12-20 16:31 UTC
